//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodBankManagementSystemm
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblDonor
    {
        public int DNum { get; set; }
        public string DName { get; set; }
        public int DAge { get; set; }
        public string DGender { get; set; }
        public string DPhone { get; set; }
        public string DAddress { get; set; }
        public string DBGroup { get; set; }
    }
}
