//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodBankManagementSystemm
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLEmployee
    {
        public int ENum { get; set; }
        public string EID { get; set; }
        public string EPass { get; set; }
    }
}
