//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodBankManagementSystemm
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPatient
    {
        public int PNum { get; set; }
        public string PName { get; set; }
        public int PAge { get; set; }
        public string PGender { get; set; }
        public string PPhone { get; set; }
        public string PAddress { get; set; }
        public string PBGroup { get; set; }
    }
}
